Fix ObjectOptimisticLockingFailureException
filling a generated ID will cause this exception
https://discourse.hibernate.org/t/facing-with-objectoptimisticlocking-failureexception-after-migrating-to-hibernate-6-6-2-final/10725/22

org.springframework.orm.ObjectOptimisticLockingFailureException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [de.cyclingsir.cetrack.tour.storage.TourEntity#eace2127-8ee1-45ad-a12e-5f2be4bb7732]] with root cause

org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [de.cyclingsir.cetrack.tour.storage.TourEntity